package com.revature.alchemyapp.exceptions;

public class UsernameAlreadyExistsException extends Exception {

}
